apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-ui
  namespace: retail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-ui
  template:
    metadata:
      labels:
        app: retail-ui
    spec:
      containers:
        - name: retail-ui
          image: suissitakwa/retail-ui:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: retail-ui
  namespace: retail-dev
spec:
  selector:
    app: retail-ui
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
